// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace Web.FClient {
	
	
	public partial class Upload {
		
		protected System.Web.UI.HtmlControls.HtmlInputFile File1;
		
		protected System.Web.UI.HtmlControls.HtmlForm Form1;
		
		protected System.Web.UI.HtmlControls.HtmlInputFile filMyFile;
		
		protected System.Web.UI.WebControls.Label lblAttachmentError;
		
		protected System.Web.UI.WebControls.Button btnUpload;
		
		protected System.Web.UI.WebControls.Label lblAttachment;
	}
}
